# Generated by Django 3.1.12 on 2021-09-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default_pp.png', upload_to='profile_pictures', verbose_name='picture'),
        ),
    ]
