version: "3.9"

services:
  web:
    build:
      context: .
    restart: unless-stopped
    container_name: qenea-backend
    volumes:
      - static_volume:${STATIC_ROOT}
    ports:
      - ${WEB_PORT}:8000
    depends_on:
      - rabbitmq
      - redis

  nginx:
    build:
      context: ./nginx
    restart: always
    container_name: nginx
    volumes:
      - static_volume:${STATIC_ROOT}
    ports:
      - 80:80
    depends_on:
      - web

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq
    restart: always
    ports:
     - 5672:5672

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis-server
    restart: always
    ports:
      - 6379:6379

  celery:
    build:
      context: .
    container_name: celery-worker
    command: celery -A qenea_backend worker -l INFO
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - redis
      - web

volumes:
  static_volume:
