# Generated by Django 3.0.4 on 2020-09-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0002_auto_20200921_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
