# Generated by Django 3.1.12 on 2021-11-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0004_auto_20211109_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
