# Generated by Django 3.0.7 on 2020-10-13 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questans', '0005_auto_20201013_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='downvotes',
            field=models.ManyToManyField(related_name='question_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='upvotes',
            field=models.ManyToManyField(related_name='question_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
