# Generated by Django 3.0.7 on 2020-12-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0007_auto_20201122_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_posted']},
        ),
    ]
