# Generated by Django 3.1.12 on 2021-12-22 16:22

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Oops! A user with email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Oops! This username is taken, please try another one.'}, max_length=25, unique=True, validators=[accounts.validators.validate_username], verbose_name='username'),
        ),
    ]
